### ISSUE TITLE
Is this openam web agents in nginx?

### ISSUE THREAD

**Issue by Git-Rajkumar** [hamano/nginx-mod-am#11]
I need openam web agents  for nginx, i tried for forgerock official site, its only for apache an micro soft IIS not for  nginx.

so, i searched about "**OpenAM Policy Agent for NGINX"** then follow your documents to  install nginx web agents.

  1. **./bin/agentadmin.sh**

is says ==> **Welcome to the OpenSSO Policy Agent for NGINX**

               ************************************************************************
		Welcome to the OpenSSO Policy Agent for NGINX
		************************************************************************

		Enter the URL where the OpenAM server is running.
		Please include the deployment URI also as shown below:
		(http://opensso.sample.com:58080/opensso)
		OpenSSO server URL:

But, your Docuement says  OpenAm Policy Agent for NGINX 

I  before **install apache_ webagent,** it asking below question:

                Apache Server Config Directory : /path/to/apache/conf
		OpenAM server URL : http://openam.example.com:8080/openam
		Agent URL : http://www.example.com:8000
		Agent Profile name : WebAgent
		Agent Profile Password file name : /tmp/pwd.txt

Why?,  is this openam Web agent or opensso web agent?

if is this openam webagent, suggest me How can i configure, like apache Configuration to Nginx web agents.

Note: i download   **20160226 Release**  for **Debian/Ubuntu x86_64**

**Comment by hamano** [comment]
Yes, This is OpenAM NGINX agent.
It's just example string, fixed it: 41a6ce8f5e5fa0895c1d2cd8fe22864e9a575760￼
