### ISSUE TITLE
OpenAm Recirect to Forbidden Page

### ISSUE THREAD

**Issue by Git-Rajkumar** [hamano/nginx-mod-am#14]
I have installed **nginx_agent and configure to openam**, now, **call nginx_agent url**, its **redirect to Openam**, **after authenticate, its throw forbidden page**.

What I did:

   **Machine-1:**
    1. install openam 
    **opeam url** ==> openam.test.mobi:8080/openam

   Configuration:
    
   1.Policy Sets
    I have Configure **openam Policy Sets**  to add  resource url to my **nginx Web apllication** running url:

          nginx.test.mobi:80

  2. webagent:
   i have create a new web agent for nginx Configuration.
           agent name : nginx
           openam url => http://opeam.test.mobi:8080/openam
          agent url ==> http://nginx.test.mobi:8000/
         pass ==> xxxxx

 **Machine-2:**

  1. i**nstall nginx server** and setup to run my web application(magento)
            nginx url ==> nginx.test.mobi:80
  2. **install nginx_agent**
           nginx_agent url ==> http://nginx.test.mobi:8000

 **./bin/agentadmin.sh**

            Openam Url ==> http://opeam.test.mobi:8080/openam 
           webagent name ==> nginx
           pass  ==> xxxxx

  **./bin/nginx**

After that  I call My nginx_agent Url  
  
           nginx.test.mobi:8000

Its **Redirected to Openam**, **after authenticate ,its redirected to forbidden page**.

**Why?**

**I need to  use openam for login purpose in my webapplication,   if i click login button in web application , its redirected to openam , then, after authenticated then show  my web application.** 

 Suggest Me, How do i configure this? below is my nginx_agent  Configuration suggest me what i miss Configured.

**nginx_agent conf:**

        worker_processes  1;
        error_log   logs/error.log;
        events {
            worker_connections  1024;
        }
        http {
            include       mime.types;
            default_type  application/octet-stream;
            sendfile        on;
            keepalive_timeout  65;
            am_boot_file "conf/OpenSSOAgentBootstrap.properties";
           # am_conf_file "conf/OpenSSOAgentConfiguration.properties";

           upstream backend {
                 server nginx.gworks.mobi:80;      // to redirect to my  web application(magento)
              }

              server {
                  listen 8000;
                  server_name  nginx.test.mobi;

                  location / {
                      proxy_pass http://backend;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;

                      include /etc/nginx/proxy_params;
                  }
                }
              }

**Comment by hamano** [comment]
> its throw forbidden page.

It's just follow your policy that set on OpenAM.
You can distingush issue to set "SSO only mode" with OpenAM.
try SSO only mode.

**Comment by Git-Rajkumar** [comment]
@hamano  million's thanks,  its works like charm.
